/**
 * @file config.h
 * @brief Compile-time background layer/rendering limits.
 */

#ifndef UNSIGNED_LEVEL_BACKGROUND_CONFIG_H
#define UNSIGNED_LEVEL_BACKGROUND_CONFIG_H

#ifndef UNSIGNED_BACKGROUND_MAX_LAYERS
#define UNSIGNED_BACKGROUND_MAX_LAYERS 3
#endif

#ifndef UNSIGNED_BACKGROUND_RENDER_MAX_COLUMNS
#define UNSIGNED_BACKGROUND_RENDER_MAX_COLUMNS 21
#endif

#if UNSIGNED_BACKGROUND_MAX_LAYERS < 1 || UNSIGNED_BACKGROUND_MAX_LAYERS > 255
#error "UNSIGNED_BACKGROUND_MAX_LAYERS must fit the non-zero u8 layer count"
#endif

#if UNSIGNED_BACKGROUND_RENDER_MAX_COLUMNS < 1 || UNSIGNED_BACKGROUND_RENDER_MAX_COLUMNS > 255
#error "UNSIGNED_BACKGROUND_RENDER_MAX_COLUMNS must fit the non-zero u8 column count"
#endif

#endif
