/**
 * @file colors.h
 * @brief Provides common Neo Geo palette colors.
 */

#ifndef UNSIGNED_CORE_COLORS_H
#define UNSIGNED_CORE_COLORS_H

#define UNSIGNED_COLOR_BLACK 0x8000u
#define UNSIGNED_COLOR_DARK_GRAY 0x8444u
#define UNSIGNED_COLOR_GRAY 0x8888u
#define UNSIGNED_COLOR_LIGHT_GRAY 0x8cccu
#define UNSIGNED_COLOR_WHITE 0x7fffu

#define UNSIGNED_COLOR_RED 0x4f00u
#define UNSIGNED_COLOR_DARK_RED 0x8800u
#define UNSIGNED_COLOR_GREEN 0x20f0u
#define UNSIGNED_COLOR_DARK_GREEN 0x8080u
#define UNSIGNED_COLOR_BLUE 0x100fu
#define UNSIGNED_COLOR_DARK_BLUE 0x8008u

#define UNSIGNED_COLOR_YELLOW 0x6ff0u
#define UNSIGNED_COLOR_ORANGE 0x4f80u
#define UNSIGNED_COLOR_BROWN 0x8840u
#define UNSIGNED_COLOR_CYAN 0x30ffu
#define UNSIGNED_COLOR_TEAL 0x8088u
#define UNSIGNED_COLOR_MAGENTA 0x5f0fu
#define UNSIGNED_COLOR_PURPLE 0x8808u
#define UNSIGNED_COLOR_PINK 0x4f8cu
#define UNSIGNED_COLOR_OLIVE 0x8880u

#endif
