/**
 * @file config.h
 * @brief Compile-time audio queue/catalog limits.
 */

#ifndef UNSIGNED_AUDIO_CONFIG_H
#define UNSIGNED_AUDIO_CONFIG_H

#ifndef UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY
#ifdef UNSIGNED_GAME_MAX_PENDING_SOUND_EFFECTS
#define UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY UNSIGNED_GAME_MAX_PENDING_SOUND_EFFECTS
#else
#define UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY 8
#endif
#endif

#ifndef UNSIGNED_GAME_MAX_PENDING_SOUND_EFFECTS
#define UNSIGNED_GAME_MAX_PENDING_SOUND_EFFECTS UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY
#endif

#ifndef UNSIGNED_AUDIO_MAX_EVENTS
#define UNSIGNED_AUDIO_MAX_EVENTS 16
#endif

#ifndef UNSIGNED_AUDIO_MAX_PARAMETERS
#define UNSIGNED_AUDIO_MAX_PARAMETERS 8
#endif

#ifndef UNSIGNED_AUDIO_MAX_VARIANTS_PER_SET
#define UNSIGNED_AUDIO_MAX_VARIANTS_PER_SET 16
#endif

#if UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY < 1 || UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY > 255
#error "UNSIGNED_AUDIO_SFX_QUEUE_CAPACITY must fit the non-zero u8 queue count"
#endif

#if UNSIGNED_AUDIO_MAX_EVENTS < 1 || UNSIGNED_AUDIO_MAX_EVENTS > 255
#error "UNSIGNED_AUDIO_MAX_EVENTS must fit the non-zero u8 event count"
#endif

#if UNSIGNED_AUDIO_MAX_PARAMETERS < 1 || UNSIGNED_AUDIO_MAX_PARAMETERS > 255
#error "UNSIGNED_AUDIO_MAX_PARAMETERS must fit the non-zero u8 parameter count"
#endif

#if UNSIGNED_AUDIO_MAX_VARIANTS_PER_SET < 1 || UNSIGNED_AUDIO_MAX_VARIANTS_PER_SET > 16
#error "UNSIGNED_AUDIO_MAX_VARIANTS_PER_SET must be between 1 and 16"
#endif

#endif
