#ifndef UNSIGNED_H
#define UNSIGNED_H

/*
 * Automatically generated.
 * Do not edit manually.
 */

#include <actor/actor.h>
#include <actor/actor_sort.h>
#include <actor/character.h>
#include <actor/collision_state.h>
#include <actor/npc.h>
#include <actor/npc_ai.h>
#include <actor/npc_config.h>
#include <actor/npc_pool.h>
#include <actor/object.h>
#include <actor/object_pool.h>
#include <actor/player.h>
#include <actor/player_config.h>
#include <actor/player_pool.h>
#include <actor/pools.h>
#include <actor/projectile.h>
#include <actor/projectile_pool.h>
#include <actor/shadow.h>
#include <audio/audio.h>
#include <audio/audio_backend.h>
#include <audio/audio_config.h>
#include <audio/audio_event.h>
#include <audio/audio_music.h>
#include <audio/audio_music_internal.h>
#include <audio/audio_queue_internal.h>
#include <audio/audio_resolver_internal.h>
#include <audio/audio_types.h>
#include <collision/actor_collision.h>
#include <collision/actor_index.h>
#include <collision/collision_config.h>
#include <collision/hit_detection.h>
#include <collision/hit_scan.h>
#include <collision/projectile_collision.h>
#include <core/colors.h>
#include <core/math/math.h>
#include <core/pool/pool.h>
#include <core/state/state_config.h>
#include <core/state/state_graph.h>
#include <core/state/state_graph_clock.h>
#include <core/timer/timer.h>
#include <core/timer/timer_config.h>
#include <core/timer/timer_pool.h>
#include <core/tlss/tlss.h>
#include <core/types.h>
#include <display/camera/camera.h>
#include <display/camera/camera_internal.h>
#include <display/effect/blink.h>
#include <display/effect/bob.h>
#include <display/effect/effect.h>
#include <display/effect/effect_compose.h>
#include <display/effect/effect_internal.h>
#include <display/effect/shake.h>
#include <display/effect/shear.h>
#include <display/effect/transform.h>
#include <display/effect/turn.h>
#include <display/effect/wave.h>
#include <display/effect/zoom.h>
#include <display/sprite/limits.h>
#include <display/sprite/palette.h>
#include <display/sprite/render_state.h>
#include <display/sprite/scale.h>
#include <display/sprite/sprite.h>
#include <display/sprite/sprite_config.h>
#include <display/text/text.h>
#include <display/ui/collection_internal.h>
#include <display/ui/context.h>
#include <display/ui/element.h>
#include <display/ui/layout.h>
#include <display/ui/menu.h>
#include <display/ui/page.h>
#include <display/ui/renderer.h>
#include <display/ui/screen.h>
#include <display/ui/theme.h>
#include <display/ui/ui_blink.h>
#include <display/ui/ui_config.h>
#include <display/ui/ui_input.h>
#include <display/ui/ui_types.h>
#include <display/ui/widget/blink_label.h>
#include <display/ui/widget/button.h>
#include <display/ui/widget/image.h>
#include <display/ui/widget/label.h>
#include <display/ui/widget/panel.h>
#include <display/ui/widget/progress_bar.h>
#include <display/ui/widget/selector.h>
#include <game/game.h>
#include <game/game_config.h>
#include <game/game_internal.h>
#include <gameplay/ability.h>
#include <gameplay/ability_pool.h>
#include <gameplay/attribute.h>
#include <gameplay/cue.h>
#include <gameplay/cue_pool.h>
#include <gameplay/effect_pool.h>
#include <gameplay/gameplay.h>
#include <gameplay/gameplay_config.h>
#include <gameplay/gameplay_effect.h>
#include <gameplay/gameplay_pool.h>
#include <gameplay/gameplay_runtime.h>
#include <gameplay/tag.h>
#include <input/input.h>
#include <level/background/background.h>
#include <level/background/background_config.h>
#include <level/level.h>
#include <level/level_camera.h>
#include <level/level_definition.h>
#include <level/level_internal.h>
#include <level/level_manager.h>
#include <level/level_runtime.h>
#include <physics/collision.h>
#include <physics/collision_box.h>
#include <physics/movement.h>
#include <physics/trajectory.h>
#include <physics/trajectory_path.h>
#include <physics/trajectory_projection.h>
#include <renderer/actor_renderer.h>
#include <renderer/background_renderer.h>
#include <renderer/background_upload.h>
#include <renderer/level_renderer.h>
#include <renderer/prepared_column.h>
#include <renderer/render_plan.h>
#include <renderer/renderer_config.h>
#include <renderer/sprite_column_plan.h>
#include <renderer/sprite_internal.h>
#include <renderer/sprite_renderer.h>
#include <renderer/ui_renderer.h>
#include <save/block.h>
#include <save/save.h>
#include <save/save_backend.h>
#include <save/save_internal.h>
#include <save/save_record_internal.h>
#include <save/set.h>
#include <save/storage.h>
#include <save/storage_internal.h>
#include <system/audio_backend_internal.h>
#include <system/background_backend.h>
#include <system/bios_callbacks_internal.h>
#include <system/bios_state_internal.h>
#include <system/credits.h>
#include <system/credits_internal.h>
#include <system/fix.h>
#include <system/frame.h>
#include <system/palette_backend.h>
#include <system/renderer_backend.h>
#include <system/session.h>
#include <system/session_internal.h>
#include <system/settings.h>
#include <system/sprite_backend.h>
#include <system/system_config.h>
#include <system/system_input.h>
#include <system/system_runtime.h>
#include <system/video.h>
#include <system/vram_writer.h>

#endif /* UNSIGNED_H */
