#ifndef UNSIGNED_H
#define UNSIGNED_H

/*
 * Automatically generated.
 * Do not edit manually.
 */

#include <actor/actor.h>
#include <actor/actor_sort.h>
#include <actor/character.h>
#include <actor/collision_state.h>
#include <actor/npc.h>
#include <actor/npc_ai.h>
#include <actor/npc_config.h>
#include <actor/npc_pool.h>
#include <actor/object.h>
#include <actor/object_pool.h>
#include <actor/player.h>
#include <actor/player_pool.h>
#include <actor/pools.h>
#include <actor/projectile.h>
#include <actor/projectile_pool.h>
#include <audio/audio.h>
#include <audio/audio_backend.h>
#include <audio/audio_event.h>
#include <audio/audio_music.h>
#include <audio/audio_music_internal.h>
#include <audio/audio_resolver_internal.h>
#include <audio/audio_types.h>
#include <audio/config.h>
#include <collision/actor_collision.h>
#include <collision/actor_index.h>
#include <collision/config.h>
#include <collision/hit_detection.h>
#include <collision/projectile_collision.h>
#include <core/colors.h>
#include <core/math/math.h>
#include <core/pool/pool.h>
#include <core/state/config.h>
#include <core/state/state_graph.h>
#include <core/timer/config.h>
#include <core/timer/timer.h>
#include <core/timer/timer_pool.h>
#include <core/tlss/tlss.h>
#include <core/types.h>
#include <display/camera/camera.h>
#include <display/sprite/attributes.h>
#include <display/sprite/limits.h>
#include <display/sprite/palette.h>
#include <display/sprite/render_state.h>
#include <display/sprite/sprite.h>
#include <display/text/text.h>
#include <display/ui/blink.h>
#include <display/ui/config.h>
#include <display/ui/context.h>
#include <display/ui/element.h>
#include <display/ui/input.h>
#include <display/ui/layout.h>
#include <display/ui/menu.h>
#include <display/ui/page.h>
#include <display/ui/renderer.h>
#include <display/ui/screen.h>
#include <display/ui/theme.h>
#include <display/ui/types.h>
#include <display/ui/widget/blink_label.h>
#include <display/ui/widget/button.h>
#include <display/ui/widget/image.h>
#include <display/ui/widget/label.h>
#include <display/ui/widget/panel.h>
#include <display/ui/widget/progress_bar.h>
#include <display/ui/widget/selector.h>
#include <display/viewport/effect.h>
#include <display/viewport/effect_shake.h>
#include <display/viewport/effect_shear.h>
#include <display/viewport/effect_wave.h>
#include <display/viewport/viewport.h>
#include <game/config.h>
#include <game/game.h>
#include <game/game_internal.h>
#include <gameplay/ability.h>
#include <gameplay/ability_pool.h>
#include <gameplay/attribute.h>
#include <gameplay/config.h>
#include <gameplay/cue.h>
#include <gameplay/cue_pool.h>
#include <gameplay/effect.h>
#include <gameplay/effect_pool.h>
#include <gameplay/gameplay.h>
#include <gameplay/gameplay_pool.h>
#include <gameplay/runtime.h>
#include <gameplay/tag.h>
#include <input/input.h>
#include <level/background/background.h>
#include <level/background/config.h>
#include <level/level.h>
#include <level/level_actor.h>
#include <level/level_collision.h>
#include <level/level_definition.h>
#include <level/level_internal.h>
#include <level/level_manager.h>
#include <level/level_runtime.h>
#include <physics/collision.h>
#include <physics/collision_box.h>
#include <physics/config.h>
#include <physics/trajectory.h>
#include <physics/trajectory_path.h>
#include <physics/trajectory_projection.h>
#include <renderer/actor_renderer.h>
#include <renderer/background_renderer.h>
#include <renderer/level_renderer.h>
#include <renderer/sprite_renderer.h>
#include <renderer/ui_renderer.h>
#include <save/block.h>
#include <save/save.h>
#include <save/save_backend.h>
#include <save/save_record_internal.h>
#include <save/set.h>
#include <save/storage.h>
#include <save/storage_internal.h>
#include <system/audio_backend_internal.h>
#include <system/bios_callbacks_internal.h>
#include <system/bios_state_internal.h>
#include <system/config.h>
#include <system/credits.h>
#include <system/credits_internal.h>
#include <system/fix.h>
#include <system/input.h>
#include <system/renderer_backend.h>
#include <system/runtime.h>
#include <system/session.h>
#include <system/session_internal.h>
#include <system/settings.h>
#include <system/video.h>
#include <system/vram_writer_internal.h>

#endif /* UNSIGNED_H */
